//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cringules.NGram.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cringules.NGram.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Peak.
        /// </summary>
        public static string AddPeak {
            get {
                return ResourceManager.GetString("AddPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximation function.
        /// </summary>
        public static string ApproximationFunction {
            get {
                return ResourceManager.GetString("ApproximationFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cauchy.
        /// </summary>
        public static string Cauchy {
            get {
                return ResourceManager.GetString("Cauchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup.
        /// </summary>
        public static string Cleanup {
            get {
                return ResourceManager.GetString("Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficients.
        /// </summary>
        public static string Coefficients {
            get {
                return ResourceManager.GetString("Coefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine best peak approximation function.
        /// </summary>
        public static string DetermineApproximationFunction {
            get {
                return ResourceManager.GetString("DetermineApproximationFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine noise level.
        /// </summary>
        public static string DetermineNoiseLevel {
            get {
                return ResourceManager.GetString("DetermineNoiseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export As.
        /// </summary>
        public static string ExportAs {
            get {
                return ResourceManager.GetString("ExportAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian.
        /// </summary>
        public static string Gaussian {
            get {
                return ResourceManager.GetString("Gaussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import File....
        /// </summary>
        public static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorentzian.
        /// </summary>
        public static string Lorentzian {
            get {
                return ResourceManager.GetString("Lorentzian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise level.
        /// </summary>
        public static string NoiseLevel {
            get {
                return ResourceManager.GetString("NoiseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Approximation.
        /// </summary>
        public static string PeakApproximation {
            get {
                return ResourceManager.GetString("PeakApproximation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaks.
        /// </summary>
        public static string Peaks {
            get {
                return ResourceManager.GetString("Peaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start Analysis.
        /// </summary>
        public static string StartAnalysis {
            get {
                return ResourceManager.GetString("StartAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wave Length.
        /// </summary>
        public static string WaveLength {
            get {
                return ResourceManager.GetString("WaveLength", resourceCulture);
            }
        }
    }
}
