//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cringules.NGram.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cringules.NGram.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Peak.
        /// </summary>
        public static string AddPeak {
            get {
                return ResourceManager.GetString("AddPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F4}.
        /// </summary>
        public static string AngleDegreesTemplate {
            get {
                return ResourceManager.GetString("AngleDegreesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle, °.
        /// </summary>
        public static string AngleHeading {
            get {
                return ResourceManager.GetString("AngleHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximate.
        /// </summary>
        public static string Approximate {
            get {
                return ResourceManager.GetString("Approximate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximated Integral Intensity, a.u..
        /// </summary>
        public static string ApproximatedIntegralIntensity {
            get {
                return ResourceManager.GetString("ApproximatedIntegralIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximation function.
        /// </summary>
        public static string ApproximationFunction {
            get {
                return ResourceManager.GetString("ApproximationFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximation Ratio, %.
        /// </summary>
        public static string ApproximationRatio {
            get {
                return ResourceManager.GetString("ApproximationRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.u..
        /// </summary>
        public static string ArbitraryUnits {
            get {
                return ResourceManager.GetString("ArbitraryUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficients.
        /// </summary>
        public static string Coefficients {
            get {
                return ResourceManager.GetString("Coefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting value to cell is not supported.
        /// </summary>
        public static string ConvertingValueToCellNotSupportedError {
            get {
                return ResourceManager.GetString("ConvertingValueToCellNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation.
        /// </summary>
        public static string Corr {
            get {
                return ResourceManager.GetString("Corr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Peak.
        /// </summary>
        public static string DeletePeak {
            get {
                return ResourceManager.GetString("DeletePeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine best peak approximation function.
        /// </summary>
        public static string DetermineApproximationFunction {
            get {
                return ResourceManager.GetString("DetermineApproximationFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine coefficients automatically.
        /// </summary>
        public static string DetermineCoefficientsAutomatically {
            get {
                return ResourceManager.GetString("DetermineCoefficientsAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine noise level.
        /// </summary>
        public static string DetermineSmoothingDegree {
            get {
                return ResourceManager.GetString("DetermineSmoothingDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffractogram Data.
        /// </summary>
        public static string DiffractogramDataHeader {
            get {
                return ResourceManager.GetString("DiffractogramDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance, Å.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F5}.
        /// </summary>
        public static string DistanceAngstromTemplate {
            get {
                return ResourceManager.GetString("DistanceAngstromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable smoothing.
        /// </summary>
        public static string EnableSmoothing {
            get {
                return ResourceManager.GetString("EnableSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export As.
        /// </summary>
        public static string ExportAs {
            get {
                return ResourceManager.GetString("ExportAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width, °.
        /// </summary>
        public static string FullWidthHalfMaximum {
            get {
                return ResourceManager.GetString("FullWidthHalfMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian.
        /// </summary>
        public static string Gaussian {
            get {
                return ResourceManager.GetString("Gaussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import Data....
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral Intensity, a.u..
        /// </summary>
        public static string IntegralIntensity {
            get {
                return ResourceManager.GetString("IntegralIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral Width, °.
        /// </summary>
        public static string IntegralWidth {
            get {
                return ResourceManager.GetString("IntegralWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string Intensity {
            get {
                return ResourceManager.GetString("Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2}.
        /// </summary>
        public static string IntensityArbitraryUnitsTemplate {
            get {
                return ResourceManager.GetString("IntensityArbitraryUnitsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda.
        /// </summary>
        public static string Lambda {
            get {
                return ResourceManager.GetString("Lambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LeftSymmetrization {
            get {
                return ResourceManager.GetString("LeftSymmetrization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorentzian.
        /// </summary>
        public static string Lorentzian {
            get {
                return ResourceManager.GetString("Lorentzian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Plot.
        /// </summary>
        public static string MainPlotTabHeader {
            get {
                return ResourceManager.GetString("MainPlotTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGram Analyzer.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Intensity, a.u..
        /// </summary>
        public static string MaxIntensity {
            get {
                return ResourceManager.GetString("MaxIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Approximation.
        /// </summary>
        public static string PeakApproximation {
            get {
                return ResourceManager.GetString("PeakApproximation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Data.
        /// </summary>
        public static string PeakDataHeader {
            get {
                return ResourceManager.GetString("PeakDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this peak?.
        /// </summary>
        public static string PeakDeleteQuestion {
            get {
                return ResourceManager.GetString("PeakDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Plot.
        /// </summary>
        public static string PeakPlotTabHeader {
            get {
                return ResourceManager.GetString("PeakPlotTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaks.
        /// </summary>
        public static string Peaks {
            get {
                return ResourceManager.GetString("Peaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F3}.
        /// </summary>
        public static string RatioTemplate {
            get {
                return ResourceManager.GetString("RatioTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Integral Intensity, %.
        /// </summary>
        public static string RelativeIntegralIntensity {
            get {
                return ResourceManager.GetString("RelativeIntegralIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2}.
        /// </summary>
        public static string RelativeIntensityPercentTemplate {
            get {
                return ResourceManager.GetString("RelativeIntensityPercentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Maximum Intensity, %.
        /// </summary>
        public static string RelativeMaxIntensity {
            get {
                return ResourceManager.GetString("RelativeMaxIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string RightSymmetrization {
            get {
                return ResourceManager.GetString("RightSymmetrization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected value.
        /// </summary>
        public static string SelectedValue {
            get {
                return ResourceManager.GetString("SelectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected wave length: {0:F5} Å.
        /// </summary>
        public static string SelectedWaveLength {
            get {
                return ResourceManager.GetString("SelectedWaveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing.
        /// </summary>
        public static string Smoothing {
            get {
                return ResourceManager.GetString("Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing Degree.
        /// </summary>
        public static string SmoothingDegree {
            get {
                return ResourceManager.GetString("SmoothingDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start Analysis.
        /// </summary>
        public static string StartAnalysis {
            get {
                return ResourceManager.GetString("StartAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetrization.
        /// </summary>
        public static string Symmetrization {
            get {
                return ResourceManager.GetString("Symmetrization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Peak.
        /// </summary>
        public static string UpdatePeak {
            get {
                return ResourceManager.GetString("UpdatePeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voigt.
        /// </summary>
        public static string Voigt {
            get {
                return ResourceManager.GetString("Voigt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wave Length.
        /// </summary>
        public static string WaveLength {
            get {
                return ResourceManager.GetString("WaveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Length Selection.
        /// </summary>
        public static string WaveLengthWindowTitle {
            get {
                return ResourceManager.GetString("WaveLengthWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to NGram Analyzer! Use buttons below to start working!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
